language: java
jdk:
  - openjdk11
before_install:
  - cd rocket-symbol-service
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install verify sonar:sonar -Dsonar.projectKey=phyzicsz_rocket-symbol-server
addons:
  sonarcloud:
    organization: phyzicsz
    token:
      secure: eqHeWv54OfMn/RsOXKu6vKsycAkUQNLov6AGe3z1TtAfNut8qFbcKGr2syMawIW3tlQCSTW1t6yzWkIRjQHWzuF7C7voSesK10Pus2SkYLaf/SOmB3LJO0iZMMHE+JhMEC+m1OtEj29mmtEONTLVWY6M3oox1usmh/KMDX/K7rCz4QN2tiPxkcCz7xzP59E3jMELxnszXCGENh7bgXxWXGbr8oP7wyz6zj5Q/GqvR0Y7oTpuLfLSUJnSZ9HnBD/lZkhlOerB8zpik25VAUo/tUvsXxrchHfcPriJ6QfStDz7ifnnCMqCkwz5CbX1B3l6R+p9z0Ge/lXdMYfhWK52yKmqhjlaxNyDrsVrOzabiGXnuY41eAXRb9dJwNfzgCxBI6LD2x8QQLTXGRDfPkMuUNvXe6rO33mW3q0IUJmJj0g6W2TNZ1XBXSXj/mNZLRg5rD3fxlUMuRsy5PvZum+1tjdhtJjftpAG8FhhHHamrUKBgVsxJlf7DseGi9FFTEqSvOCDHYGjl7K4feac+M8c6xZF9cbG27L2oJqFJ91LEU86oR3IlDQKjwOFoQhD0yY7VMqw9CFr/wZ41Z1yJmpkogeB1v4OoV3O9QxlkwFG7ndwDzQ9pQfOKISggUFUmpHd2fo5/y8pmOw0ZaNJCFLhMNBGTA7Onh+5couu/40pRuE=
